### ISSUE TITLE
"src/shared/proteus/: No such file or directory" during yarn install/protoc

### ISSUE THREAD

**Issue by DavidMGross** [netifi/proteus-quickstart-js#3]
When doing the `yarn install && yarn protoc` step, I got the error `src/shared/proteus/: No such file or directory` (on both Ubuntu/16 and MacOS/Mojave).

As a workaround, `mkdir src/shared/proteus` then repeat the yarn install/protoc step.

**Comment by hypothete** [comment]
This should be fixed now, please take a look and let me know if you run into anything else.
