### ISSUE TITLE
protoc protobuf compiler not listed as prerequisite; errors result from its absence

### ISSUE THREAD

**Issue by DavidMGross** [netifi/proteus-quickstart-js#4]
https://www.netifi.com/getstarted-js does not list the protoc protobuf compiler (v3) as a prerequisite, but it is required for the success of the build.

For information on how to install protoc, see: https://github.com/protocolbuffers/protobuf/blob/master/src/README.md

**Comment by hypothete** [comment]
Hi David, thanks for pointing this out. I should have a fix out shortly that provides the JS files generated by protoc. This will also fix #3 . For people interested in experimenting with the protobufs, I've added a note in the readme that includes your installation link.
